### ISSUE TITLE
Random assert failures with same script

### ISSUE THREAD

**Issue by rockandska** [jhawthorn/ttytest#2]
Hi,

Not sure why, but the results from my test bellow are not consistent and don't get why.
Any ideas ?

```
$ tmux -V
tmux 2.6
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
$ bundler -v
Bundler version 1.16.1
$ bundle install --path vendor/bundle
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Using bundler 1.16.1
Fetching minitest 5.11.3
Installing minitest 5.11.3
Fetching ttytest 0.5.0
Installing ttytest 0.5.0
Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
Bundled gems are installed into `./vendor/bundle`
$ cat test.rb 
require 'minitest'
require 'minitest/autorun'
require 'ttytest'

class IssueTest < Minitest::Test

  def test_complete
    @tty = TTYtest.new_terminal(%{env -i PS1='$ ' /bin/bash --norc --noprofile})
    @tty.send_keys(%{source /etc/bash_completion\n})
    @tty.assert_row(2, '$')
  end

end
$ for i in {1..20};do r=$RANDOM; let "r %= 10" ;bundle exec ruby test.rb &> /dev/null; printf "%s " $?;sleep $r;done
1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 0 1 1 0
```

When the test fail, this is this output:
```
$ bundle exec ruby test.rb
Run options: --seed 17534

# Running:

E

Finished in 2.045393s, 0.4889 runs/s, 0.0000 assertions/s.

  1) Error:
IssueTest#test_complete:
TTYtest::MatchError: expected row 2 to be "$" but got ""
Entire screen:
$ source /etc/bash_completion
$






















    /tmp/ttytest/vendor/bundle/ruby/2.5.0/gems/ttytest-0.5.0/lib/ttytest/matchers.rb:11:in `assert_row'
    /tmp/ttytest/vendor/bundle/ruby/2.5.0/gems/ttytest-0.5.0/lib/ttytest/terminal.rb:56:in `public_send'
    /tmp/ttytest/vendor/bundle/ruby/2.5.0/gems/ttytest-0.5.0/lib/ttytest/terminal.rb:56:in `block (3 levels) in <class:Terminal>'
    /tmp/ttytest/vendor/bundle/ruby/2.5.0/gems/ttytest-0.5.0/lib/ttytest/terminal.rb:66:in `synchronize'
    /tmp/ttytest/vendor/bundle/ruby/2.5.0/gems/ttytest-0.5.0/lib/ttytest/terminal.rb:55:in `block (2 levels) in <class:Terminal>'
    test.rb:10:in `test_complete'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$ 
```

Regards,

**Comment by rockandska** [comment]
Adding a small sleep after creating the tmux session seem to solve the consistency of the tests

```
$ cat test.rb 
require 'minitest'
require 'minitest/autorun'
require 'ttytest'

class IssueTest < Minitest::Test

  def test_complete
    @tty = TTYtest.new_terminal(%{env -i PS1='$ ' /bin/bash --norc --noprofile})
    @tty.send_keys(%{source /etc/bash_completion\n})
    @tty.assert_row(1, '$ ')
  end

end
$ for i in {1..300};do bundle exec ruby test.rb &> /dev/null; printf "%s " $?;done
1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 $ 
$ cat test.rb 
require 'minitest'
require 'minitest/autorun'
require 'ttytest'

class IssueTest < Minitest::Test

  def test_complete
    @tty = TTYtest.new_terminal(%{env -i PS1='$ ' /bin/bash --norc --noprofile})
    sleep(0.5)
    @tty.send_keys(%{source /etc/bash_completion\n})
    @tty.assert_row(1, '$ ')
  end

end
$ for i in {1..300};do bundle exec ruby test.rb &> /dev/null; printf "%s " $?;done
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 $ 
```
